version: '2.2'

networks:
  database:
    driver: bridge

services:
  server:
    build: ./server
    restart: always
    links:
      - db
    expose:
      - $PORT
    environment:
      - DB_HOST=db
      - PORT=$PORT
      - TZ="Europe/Copenhagen"
    networks:
      - database
  db:
    build: ./db    
    restart: always
    networks:
      - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webshop
      TZ: "Europe/Copenhagen"
    expose:
      - 5432
    volumes:
      - ./db/data:/var/lib/postgresql/data/
