version: '2.2'

networks:
  database:
    driver: bridge

services:
  server:
    build: ./server
    restart: always
    links:
      - db
    ports:
      - 3000:$PORT
    environment:
      - DB_HOST=db
      - PORT=$PORT
      - TZ="Europe/Copenhagen"
    networks:
      - database
  db:
    image: postgres:13-alpine    
    restart: always
    networks:
      - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webshop
      TZ: "Europe/Copenhagen"
    expose:
      - 5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:z
      - ./db/data:/var/lib/postgresql/data:z
